name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      # Node.js 20 actions are deprecated. To opt into Node.js 24 now, set the FORCE_JAVASCRIPT_ACTIONS_TO_NODE24=true
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'
    strategy:
      matrix:
        # NOTICE: "windows-latest" requests are being redirected to "windows-2025-vs2026" by June 15, 2026
        os: [ubuntu-latest, windows-2025-vs2026]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal
